service: basic-project

provider:
  name: aws
  runtime: python3.8
  versionFunctions: false
  memorySize: 128
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: dev/info
          method: get